package com.netease.example.demo.service;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.netease.example.demo.entity.User;
import com.netease.example.demo.repository.UserRepository;

@Service
public class UserServiceImpl implements UserService{
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@Override
	@Transactional
	public User save(User u) {
		userRepository.save(u);
		return u;
	}
	
	

}
